# Stage 1: Build Hugo site
FROM docker.io/alpine:latest AS builder

# Install Hugo v0.166.0
RUN apk add --no-cache wget tar && \
    wget -q https://github.com/gohugoio/hugo/releases/download/v0.166.0/hugo_0.166.0_linux-arm64.tar.gz && \
    tar xzf hugo_0.166.0_linux-arm64.tar.gz && \
    mv hugo /usr/local/bin/ && \
    rm hugo_0.166.0_linux-arm64.tar.gz

WORKDIR /src
COPY hugo-site/ .
RUN hugo --minify --gc

# Stage 2: Serve with Nginx
FROM docker.io/nginx:1.28.0-alpine

LABEL maintainer="Jorge Villavicencio <jorge.a.villavicencio@gmail.com>"

COPY --from=builder /src/public/ /usr/share/nginx/html
COPY hugo-site/nginx/ /etc/nginx/conf.d

EXPOSE 80