baseURL = 'http://odesa.local:8081'
languageCode = 'en-us'
title = 'My Own Tech Views'
theme = 'papermod'

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'